name: Movie Clips

on:
  schedule:
    # daily at 10:00 AM Eastern = 14:00 UTC
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install -r requirements.txt yt-dlp

    - name: Write service account file
      run: echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT }}' > service_account.json
    
    - name: Display service account file for debugging
      run: cat service_account.json

    - name: Run movie_clips.py
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: python movie_clips.py
