name: NBA Processor
on:
  schedule:
    - cron: '30 15 * * *'  # 10:30 AM EST
  workflow_dispatch:
jobs:
  process-nba:
    runs-on: ubuntu-latest
    env:
      GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        pip install -r requirements.txt
        sudo apt-get install -y ffmpeg
    - run: python NBA.py
