name: Run NFL Video Bot

on:
  schedule:
    - cron: '00 14 * * *'  # 10:00 AM EST (14:00 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U --pre "yt-dlp[all]"
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Run NFL-2 Video Bot
      env:
        REDDIT_CLIENT_ID:       ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET:   ${{ secrets.REDDIT_CLIENT_SECRET }}
        OPENROUTER_API_KEY:     ${{ secrets.OPENROUTER_API_KEY }}
        GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: python NFL-2.py
