name: Run NFL Video Bot

on:
  schedule:
    - cron: '30 14 * * *'  # 10:30 AM EST
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U --pre "yt-dlp[all]"
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Merge Reddit & YouTube cookies
      run: |
        # preserve the Netscape header
        head -n 3 cookies.txt > merged_cookies.txt
        # append the rest of reddit cookies
        tail -n +4 cookies.txt >> merged_cookies.txt
        # append the rest of YouTube cookies
        tail -n +4 YT_Cookies.txt >> merged_cookies.txt
        # overwrite cookies.txt
        mv merged_cookies.txt cookies.txt
        echo "✅ cookies.txt now contains both Reddit & YouTube cookies"

    - name: Run NFL-2 Video Bot
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
      run: python NFL-2.py
