name: Run Poly Bot

on:
  schedule:
    - cron: '30 14 * * *'   # 10:30 AM EST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENROUTER_API_KEY:     ${{ secrets.OPENROUTER_API_KEY }}
      GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install snscrape "yt-dlp[all]" requests google-api-python-client google-auth

      - name: Run bot
        run: python poly.py
