name: Daily Video Processor

on:
  schedule:
    - cron: '30 15 * * *'  # 10:30 AM EST (15:30 UTC)
  workflow_dispatch:

jobs:
  process_videos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install snscrape yt-dlp[all] --pre
        pip install requests==2.31.0 "urllib3<2.2" certifi google-api-python-client google-auth

    - name: Configure SSL
      run: |
        sudo cp $(python -c 'import certifi; print(certifi.where())') /etc/ssl/certs/ca-certificates.crt
        sudo update-ca-certificates

    - name: Run video processor
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        PYTHONHTTPSVERIFY: 0
      run: python poly.py
