name: Run Poly Video Bot

on:
  schedule:
    - cron: '30 14 * * *'   # 10:30 AM EST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg ca-certificates

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install snscrape
          pip install -U --pre "yt-dlp[all]"
          pip install requests google-api-python-client google-auth

      - name: Run poly.py
        env:
          OPENROUTER_API_KEY:     ${{ secrets.OPENROUTER_API_KEY }}
          GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        run: python poly.py
