name: Upload Funny Videos to YouTube

on:
  schedule:
    - cron: '0 22 * * *'   # daily at 22:00 UTC = 6 PM ET
  workflow_dispatch:

jobs:
  upload-funny:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth google-auth-httplib2

      - name: Run Funny uploader
        env:
          FUNNY_YT_TOKEN:        ${{ secrets.FUNNY_YT_TOKEN }}
          GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        run: python upload_funny_videos.py
